"""Japan Travel Navi - Spot database with 50 locations across 5 categories."""

SPOTS = [
    # ==================== TEMPLES/SHRINES (1-10) ====================
    {
        "slug": "fushimi-inari",
        "en": {
            "title": "Fushimi Inari Shrine - 10,000 Vermillion Torii Gates",
            "category": "Temples",
            "city": "Kyoto",
            "description": "Explore the magical Fushimi Inari Shrine with its thousands of vibrant torii gates winding through the forested hills of Kyoto.",
        },
        "ja": {
            "title": "伏見稲荷大社 - 千本鳥居の絶景",
            "category": "寺社仏閣",
            "city": "京都",
            "description": "京都の山を縫うように連なる朱色の鳥居のトンネル。伏見稲荷大社の魅力を徹底紹介。",
        },
        "zh": {
            "title": "伏见稻荷大社 - 万座朱红色鸟居",
            "category": "寺庙",
            "city": "京都",
            "description": "探索伏见稻荷大社，数千座朱红色鸟居蜿蜒穿过京都的山林。",
        },
        "ko": {
            "title": "후시미이나리 신사 - 만 개의 주홍 도리이",
            "category": "사찰",
            "city": "교토",
            "description": "교토 산속을 누비는 수천 개의 주홍색 도리이. 후시미이나리 신사의 매력을 소개합니다.",
        },
        "es": {
            "title": "Santuario Fushimi Inari - 10,000 Puertas Torii Bermellón",
            "category": "Templos",
            "city": "Kioto",
            "description": "Explora el mágico Santuario Fushimi Inari con sus miles de puertas torii serpenteando por las colinas boscosas de Kioto.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Torii_gates_at_Fushimi_Inari_Shrine_2.jpg/1280px-Torii_gates_at_Fushimi_Inari_Shrine_2.jpg",
        "tags_en": ["shrine", "torii", "kyoto", "iconic"],
        "tags_ja": ["神社", "鳥居", "京都", "名所"],
        "tags_zh": ["神社", "鸟居", "京都", "名胜"],
        "tags_ko": ["신사", "도리이", "교토", "명소"],
        "tags_es": ["santuario", "torii", "kioto", "icónico"],
    },
    {
        "slug": "kinkakuji",
        "en": {
            "title": "Kinkaku-ji - The Golden Pavilion of Kyoto",
            "category": "Temples",
            "city": "Kyoto",
            "description": "Discover Kinkaku-ji, the stunning golden temple reflected in a mirror-like pond, one of Kyoto's most iconic landmarks.",
        },
        "ja": {
            "title": "金閣寺 - 黄金に輝く京都のシンボル",
            "category": "寺社仏閣",
            "city": "京都",
            "description": "鏡湖池に映る黄金の楼閣。京都を代表する世界遺産・金閣寺の見どころを紹介。",
        },
        "zh": {
            "title": "金阁寺 - 京都的黄金殿堂",
            "category": "寺庙",
            "city": "京都",
            "description": "探索金阁寺，这座令人惊叹的金色寺庙倒映在如镜般的池塘中，是京都最具标志性的地标之一。",
        },
        "ko": {
            "title": "킨카쿠지 - 교토의 황금 누각",
            "category": "사찰",
            "city": "교토",
            "description": "거울 같은 연못에 비치는 황금 누각. 교토를 대표하는 세계유산 킨카쿠지를 소개합니다.",
        },
        "es": {
            "title": "Kinkaku-ji - El Pabellón Dorado de Kioto",
            "category": "Templos",
            "city": "Kioto",
            "description": "Descubre Kinkaku-ji, el impresionante templo dorado reflejado en un estanque cristalino, uno de los monumentos más icónicos de Kioto.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Kinkaku-ji_2023-05.jpg/1280px-Kinkaku-ji_2023-05.jpg",
        "tags_en": ["temple", "golden", "kyoto", "world-heritage"],
        "tags_ja": ["寺院", "金閣", "京都", "世界遺産"],
        "tags_zh": ["寺庙", "金阁", "京都", "世界遗产"],
        "tags_ko": ["사찰", "금각", "교토", "세계유산"],
        "tags_es": ["templo", "dorado", "kioto", "patrimonio-mundial"],
    },
    {
        "slug": "kiyomizudera",
        "en": {
            "title": "Kiyomizu-dera - The Stage Over the Valley",
            "category": "Temples",
            "city": "Kyoto",
            "description": "Visit Kiyomizu-dera, the famous wooden temple perched on a hillside with breathtaking views of Kyoto's cherry blossoms and autumn leaves.",
        },
        "ja": {
            "title": "清水寺 - 清水の舞台から望む絶景",
            "category": "寺社仏閣",
            "city": "京都",
            "description": "「清水の舞台から飛び降りる」で有名な清水寺。四季折々の絶景を堪能できる京都の名刹。",
        },
        "zh": {
            "title": "清水寺 - 悬崖上的舞台",
            "category": "寺庙",
            "city": "京都",
            "description": "参观清水寺，这座著名的木制寺庙坐落在山坡上，可欣赏京都樱花和红叶的壮丽景色。",
        },
        "ko": {
            "title": "기요미즈데라 - 계곡 위의 무대",
            "category": "사찰",
            "city": "교토",
            "description": "절벽 위에 세워진 나무 무대에서 교토의 벚꽃과 단풍을 한눈에. 기요미즈데라를 소개합니다.",
        },
        "es": {
            "title": "Kiyomizu-dera - El Escenario Sobre el Valle",
            "category": "Templos",
            "city": "Kioto",
            "description": "Visita Kiyomizu-dera, el famoso templo de madera en lo alto de una colina con vistas impresionantes de los cerezos y hojas otoñales de Kioto.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Kiyomizu-dera%2C_Kyoto%2C_November_2016_-01.jpg/1280px-Kiyomizu-dera%2C_Kyoto%2C_November_2016_-01.jpg",
        "tags_en": ["temple", "wooden-stage", "kyoto", "cherry-blossom"],
        "tags_ja": ["寺院", "清水の舞台", "京都", "桜"],
        "tags_zh": ["寺庙", "清水舞台", "京都", "樱花"],
        "tags_ko": ["사찰", "청수무대", "교토", "벚꽃"],
        "tags_es": ["templo", "escenario", "kioto", "cerezos"],
    },
    {
        "slug": "todaiji",
        "en": {
            "title": "Todai-ji - The Great Buddha of Nara",
            "category": "Temples",
            "city": "Nara",
            "description": "Marvel at Todai-ji, home to the world's largest bronze Buddha statue, set in the peaceful deer park of Nara.",
        },
        "ja": {
            "title": "東大寺 - 奈良の大仏と鹿の都",
            "category": "寺社仏閣",
            "city": "奈良",
            "description": "世界最大の木造建築に鎮座する大仏様。奈良公園の鹿と共に歩む東大寺の魅力を紹介。",
        },
        "zh": {
            "title": "东大寺 - 奈良大佛",
            "category": "寺庙",
            "city": "奈良",
            "description": "惊叹于东大寺，这里拥有世界上最大的青铜佛像，坐落在宁静的奈良鹿公园中。",
        },
        "ko": {
            "title": "도다이지 - 나라의 대불",
            "category": "사찰",
            "city": "나라",
            "description": "세계 최대의 청동 대불이 있는 도다이지. 나라 사슴공원의 평화로운 분위기와 함께 소개합니다.",
        },
        "es": {
            "title": "Todai-ji - El Gran Buda de Nara",
            "category": "Templos",
            "city": "Nara",
            "description": "Admira Todai-ji, hogar de la estatua de Buda de bronce más grande del mundo, ubicada en el tranquilo parque de ciervos de Nara.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Todaiji18s3200.jpg/1280px-Todaiji18s3200.jpg",
        "tags_en": ["temple", "buddha", "nara", "deer"],
        "tags_ja": ["寺院", "大仏", "奈良", "鹿"],
        "tags_zh": ["寺庙", "大佛", "奈良", "鹿"],
        "tags_ko": ["사찰", "대불", "나라", "사슴"],
        "tags_es": ["templo", "buda", "nara", "ciervos"],
    },
    {
        "slug": "itsukushima-shrine",
        "en": {
            "title": "Itsukushima Shrine - The Floating Torii Gate",
            "category": "Temples",
            "city": "Hiroshima",
            "description": "Witness the iconic floating torii gate of Itsukushima Shrine on Miyajima Island, one of Japan's most photographed sights.",
        },
        "ja": {
            "title": "厳島神社 - 海に浮かぶ大鳥居",
            "category": "寺社仏閣",
            "city": "広島",
            "description": "瀬戸内海に浮かぶ朱色の大鳥居。日本三景の一つ、宮島・厳島神社の絶景を紹介。",
        },
        "zh": {
            "title": "严岛神社 - 漂浮的鸟居",
            "category": "寺庙",
            "city": "广岛",
            "description": "见证严岛神社标志性的海上鸟居，宫岛上日本最常被拍摄的景点之一。",
        },
        "ko": {
            "title": "이쓰쿠시마 신사 - 바다 위의 도리이",
            "category": "사찰",
            "city": "히로시마",
            "description": "미야지마 섬의 바다 위에 떠있는 도리이. 일본 3경 중 하나인 이쓰쿠시마 신사를 소개합니다.",
        },
        "es": {
            "title": "Santuario Itsukushima - El Torii Flotante",
            "category": "Templos",
            "city": "Hiroshima",
            "description": "Contempla el icónico torii flotante del Santuario Itsukushima en la Isla Miyajima, una de las vistas más fotografiadas de Japón.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Itsukushima_Shrine_Torii_Gate_2022.jpg/1280px-Itsukushima_Shrine_Torii_Gate_2022.jpg",
        "tags_en": ["shrine", "floating-torii", "miyajima", "hiroshima"],
        "tags_ja": ["神社", "大鳥居", "宮島", "広島"],
        "tags_zh": ["神社", "海上鸟居", "宫岛", "广岛"],
        "tags_ko": ["신사", "해상도리이", "미야지마", "히로시마"],
        "tags_es": ["santuario", "torii-flotante", "miyajima", "hiroshima"],
    },
    {
        "slug": "meiji-jingu",
        "en": {
            "title": "Meiji Jingu - Tokyo's Forest Shrine",
            "category": "Temples",
            "city": "Tokyo",
            "description": "Step into the serene forest of Meiji Jingu, a Shinto shrine in the heart of Tokyo dedicated to Emperor Meiji.",
        },
        "ja": {
            "title": "明治神宮 - 都心に広がる鎮守の杜",
            "category": "寺社仏閣",
            "city": "東京",
            "description": "原宿・表参道のすぐそばに広がる神秘の森。明治天皇を祀る明治神宮の見どころを紹介。",
        },
        "zh": {
            "title": "明治神宫 - 东京的森林神社",
            "category": "寺庙",
            "city": "东京",
            "description": "步入明治神宫的宁静森林，这座位于东京市中心的神道神社纪念明治天皇。",
        },
        "ko": {
            "title": "메이지진구 - 도쿄의 숲속 신사",
            "category": "사찰",
            "city": "도쿄",
            "description": "도쿄 한복판에 펼쳐진 신비로운 숲. 메이지 천황을 모시는 메이지진구를 소개합니다.",
        },
        "es": {
            "title": "Meiji Jingu - El Santuario del Bosque de Tokio",
            "category": "Templos",
            "city": "Tokio",
            "description": "Adéntrate en el sereno bosque de Meiji Jingu, un santuario sintoísta en el corazón de Tokio dedicado al Emperador Meiji.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Meiji_Shrine_2019a.jpg/1280px-Meiji_Shrine_2019a.jpg",
        "tags_en": ["shrine", "forest", "tokyo", "meiji"],
        "tags_ja": ["神社", "森", "東京", "明治"],
        "tags_zh": ["神社", "森林", "东京", "明治"],
        "tags_ko": ["신사", "숲", "도쿄", "메이지"],
        "tags_es": ["santuario", "bosque", "tokio", "meiji"],
    },
    {
        "slug": "sensoji",
        "en": {
            "title": "Senso-ji - Tokyo's Oldest Temple in Asakusa",
            "category": "Temples",
            "city": "Tokyo",
            "description": "Explore Senso-ji, Tokyo's oldest and most famous temple, with its iconic Thunder Gate and vibrant Nakamise shopping street.",
        },
        "ja": {
            "title": "浅草寺 - 雷門と仲見世の賑わい",
            "category": "寺社仏閣",
            "city": "東京",
            "description": "雷門の大提灯が出迎える東京最古の寺院。仲見世通りの食べ歩きも楽しめる浅草寺を紹介。",
        },
        "zh": {
            "title": "浅草寺 - 东京最古老的寺庙",
            "category": "寺庙",
            "city": "东京",
            "description": "探索浅草寺，东京最古老最著名的寺庙，标志性的雷门和热闹的仲见世商店街。",
        },
        "ko": {
            "title": "센소지 - 도쿄에서 가장 오래된 아사쿠사 사찰",
            "category": "사찰",
            "city": "도쿄",
            "description": "카미나리몬의 대형 등과 나카미세 거리. 도쿄 최고(最古)의 사찰 센소지를 소개합니다.",
        },
        "es": {
            "title": "Senso-ji - El Templo Más Antiguo de Tokio en Asakusa",
            "category": "Templos",
            "city": "Tokio",
            "description": "Explora Senso-ji, el templo más antiguo y famoso de Tokio, con su icónica Puerta del Trueno y la animada calle comercial Nakamise.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Senso-ji_2012.jpg/1280px-Senso-ji_2012.jpg",
        "tags_en": ["temple", "asakusa", "tokyo", "thunder-gate"],
        "tags_ja": ["寺院", "浅草", "東京", "雷門"],
        "tags_zh": ["寺庙", "浅草", "东京", "雷门"],
        "tags_ko": ["사찰", "아사쿠사", "도쿄", "카미나리몬"],
        "tags_es": ["templo", "asakusa", "tokio", "puerta-del-trueno"],
    },
    {
        "slug": "koyasan",
        "en": {
            "title": "Koyasan - Sacred Mountain of Buddhism",
            "category": "Temples",
            "city": "Wakayama",
            "description": "Experience the mystical Koyasan, a mountaintop temple town where you can stay in Buddhist monasteries and walk through ancient cedar forests.",
        },
        "ja": {
            "title": "高野山 - 空海が開いた聖地",
            "category": "寺社仏閣",
            "city": "和歌山",
            "description": "弘法大師・空海が開いた真言密教の聖地。宿坊体験や奥之院の荘厳な雰囲気を紹介。",
        },
        "zh": {
            "title": "高野山 - 佛教圣山",
            "category": "寺庙",
            "city": "和歌山",
            "description": "体验神秘的高野山，一座山顶寺庙小镇，可入住佛教寺院，漫步于古老的杉树林中。",
        },
        "ko": {
            "title": "고야산 - 불교의 성스러운 산",
            "category": "사찰",
            "city": "와카야마",
            "description": "쿠카이가 열었던 진언밀교의 성지. 사찰 숙박과 오쿠노인의 장엄한 분위기를 소개합니다.",
        },
        "es": {
            "title": "Koyasan - La Montaña Sagrada del Budismo",
            "category": "Templos",
            "city": "Wakayama",
            "description": "Experimenta el místico Koyasan, un pueblo-templo en la montaña donde puedes alojarte en monasterios budistas y caminar por bosques de cedros centenarios.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Okunoin_01.jpg/1280px-Okunoin_01.jpg",
        "tags_en": ["temple", "mountain", "wakayama", "buddhism", "monastery"],
        "tags_ja": ["寺院", "山", "和歌山", "仏教", "宿坊"],
        "tags_zh": ["寺庙", "山", "和歌山", "佛教", "寺院住宿"],
        "tags_ko": ["사찰", "산", "와카야마", "불교", "숙방"],
        "tags_es": ["templo", "montaña", "wakayama", "budismo", "monasterio"],
    },
    {
        "slug": "izumo-taisha",
        "en": {
            "title": "Izumo Taisha - Japan's Oldest Shrine",
            "category": "Temples",
            "city": "Shimane",
            "description": "Visit Izumo Taisha, one of Japan's most ancient and important Shinto shrines, known as the home of the gods of matchmaking.",
        },
        "ja": {
            "title": "出雲大社 - 縁結びの聖地",
            "category": "寺社仏閣",
            "city": "島根",
            "description": "日本最古級の神社であり、縁結びの神様として名高い出雲大社。神在月の伝説も紹介。",
        },
        "zh": {
            "title": "出云大社 - 日本最古老的神社",
            "category": "寺庙",
            "city": "岛根",
            "description": "参观出云大社，日本最古老最重要的神道神社之一，以姻缘之神闻名。",
        },
        "ko": {
            "title": "이즈모타이샤 - 일본에서 가장 오래된 신사",
            "category": "사찰",
            "city": "시마네",
            "description": "인연맺기의 신으로 유명한 이즈모타이샤. 일본 최고(最古)의 신사를 소개합니다.",
        },
        "es": {
            "title": "Izumo Taisha - El Santuario Más Antiguo de Japón",
            "category": "Templos",
            "city": "Shimane",
            "description": "Visita Izumo Taisha, uno de los santuarios sintoístas más antiguos e importantes de Japón, conocido como el hogar de los dioses del emparejamiento.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Izumo-taisha_haiden.jpg/1280px-Izumo-taisha_haiden.jpg",
        "tags_en": ["shrine", "ancient", "shimane", "matchmaking"],
        "tags_ja": ["神社", "古代", "島根", "縁結び"],
        "tags_zh": ["神社", "古老", "岛根", "姻缘"],
        "tags_ko": ["신사", "고대", "시마네", "인연"],
        "tags_es": ["santuario", "antiguo", "shimane", "emparejamiento"],
    },
    {
        "slug": "nikko-toshogu",
        "en": {
            "title": "Nikko Toshogu - Ornate Shrine in the Mountains",
            "category": "Temples",
            "city": "Tochigi",
            "description": "Admire Nikko Toshogu, the lavishly decorated mausoleum of Tokugawa Ieyasu, nestled in the mountains north of Tokyo.",
        },
        "ja": {
            "title": "日光東照宮 - 徳川家康を祀る豪華絢爛の社",
            "category": "寺社仏閣",
            "city": "栃木",
            "description": "「日光を見ずして結構と言うなかれ」。徳川家康公の霊廟、日光東照宮の絢爛豪華な装飾を紹介。",
        },
        "zh": {
            "title": "日光东照宫 - 山中华丽神社",
            "category": "寺庙",
            "city": "枥木",
            "description": "欣赏日光东照宫，德川家康的华丽陵墓，坐落在东京北部的群山之中。",
        },
        "ko": {
            "title": "닛코 도쇼구 - 산속의 화려한 신사",
            "category": "사찰",
            "city": "도치기",
            "description": "도쿠가와 이에야스의 화려한 영묘. 도쿄 북쪽 산속에 자리한 닛코 도쇼구를 소개합니다.",
        },
        "es": {
            "title": "Nikko Toshogu - Santuario Ornamental en las Montañas",
            "category": "Templos",
            "city": "Tochigi",
            "description": "Admira Nikko Toshogu, el lujosamente decorado mausoleo de Tokugawa Ieyasu, enclavado en las montañas al norte de Tokio.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Nikko_Toshogu_Yomeimon_M3249.jpg/1280px-Nikko_Toshogu_Yomeimon_M3249.jpg",
        "tags_en": ["shrine", "tokugawa", "nikko", "ornate"],
        "tags_ja": ["神社", "徳川", "日光", "豪華"],
        "tags_zh": ["神社", "德川", "日光", "华丽"],
        "tags_ko": ["신사", "도쿠가와", "닛코", "화려"],
        "tags_es": ["santuario", "tokugawa", "nikko", "ornamental"],
    },
    # ==================== FOOD (11-20) ====================
    {
        "slug": "tokyo-ramen-guide",
        "en": {
            "title": "Tokyo Ramen Guide - Best Bowls in the Capital",
            "category": "Food",
            "city": "Tokyo",
            "description": "A comprehensive guide to Tokyo's best ramen shops, from rich tonkotsu to delicate shoyu, covering all major ramen styles.",
        },
        "ja": {
            "title": "東京ラーメンガイド - 首都圏の名店巡り",
            "category": "グルメ",
            "city": "東京",
            "description": "濃厚豚骨から淡麗系醤油まで。東京で絶対に外せないラーメンの名店を厳選して紹介。",
        },
        "zh": {
            "title": "东京拉面指南 - 首都最佳拉面",
            "category": "美食",
            "city": "东京",
            "description": "东京最佳拉面店综合指南，从浓郁豚骨到清淡酱油，涵盖所有主要拉面风格。",
        },
        "ko": {
            "title": "도쿄 라멘 가이드 - 수도의 최고 라멘",
            "category": "음식",
            "city": "도쿄",
            "description": "진한 돈코쓰부터 깔끔한 쇼유까지. 도쿄에서 꼭 가봐야 할 라멘 명점을 소개합니다.",
        },
        "es": {
            "title": "Guía de Ramen en Tokio - Los Mejores Tazones de la Capital",
            "category": "Gastronomía",
            "city": "Tokio",
            "description": "Una guía completa de las mejores tiendas de ramen de Tokio, desde el rico tonkotsu hasta el delicado shoyu.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Shoyu_ramen%2C_at_Kasukabe_Station_%282014.05.05%29_1.jpg/1280px-Shoyu_ramen%2C_at_Kasukabe_Station_%282014.05.05%29_1.jpg",
        "tags_en": ["ramen", "food", "tokyo", "noodles"],
        "tags_ja": ["ラーメン", "グルメ", "東京", "麺"],
        "tags_zh": ["拉面", "美食", "东京", "面条"],
        "tags_ko": ["라멘", "음식", "도쿄", "면"],
        "tags_es": ["ramen", "gastronomía", "tokio", "fideos"],
    },
    {
        "slug": "osaka-takoyaki",
        "en": {
            "title": "Osaka Takoyaki Tour - Street Food Paradise",
            "category": "Food",
            "city": "Osaka",
            "description": "Discover the best takoyaki in Osaka, the birthplace of these crispy-outside, gooey-inside octopus balls.",
        },
        "ja": {
            "title": "大阪たこ焼き巡り - 本場の味を食べ歩き",
            "category": "グルメ",
            "city": "大阪",
            "description": "たこ焼き発祥の地・大阪で、外はカリッと中はトロッの絶品たこ焼きを食べ歩き。名店を紹介。",
        },
        "zh": {
            "title": "大阪章鱼烧之旅 - 街头美食天堂",
            "category": "美食",
            "city": "大阪",
            "description": "发现大阪最好的章鱼烧，这里是外酥内软章鱼丸子的发源地。",
        },
        "ko": {
            "title": "오사카 타코야키 투어 - 길거리 음식 천국",
            "category": "음식",
            "city": "오사카",
            "description": "타코야키의 본고장 오사카에서 바삭하고 촉촉한 최고의 타코야키를 소개합니다.",
        },
        "es": {
            "title": "Tour de Takoyaki en Osaka - Paraíso de Comida Callejera",
            "category": "Gastronomía",
            "city": "Osaka",
            "description": "Descubre el mejor takoyaki de Osaka, la cuna de estas bolas de pulpo crujientes por fuera y cremosas por dentro.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Takoyaki_by_OiMax_in_Osaka.jpg/1280px-Takoyaki_by_OiMax_in_Osaka.jpg",
        "tags_en": ["takoyaki", "street-food", "osaka", "octopus"],
        "tags_ja": ["たこ焼き", "食べ歩き", "大阪", "たこ"],
        "tags_zh": ["章鱼烧", "街头美食", "大阪", "章鱼"],
        "tags_ko": ["타코야키", "길거리음식", "오사카", "문어"],
        "tags_es": ["takoyaki", "comida-callejera", "osaka", "pulpo"],
    },
    {
        "slug": "kyoto-matcha-sweets",
        "en": {
            "title": "Kyoto Matcha Sweets - Green Tea Heaven",
            "category": "Food",
            "city": "Kyoto",
            "description": "Indulge in Kyoto's finest matcha desserts from centuries-old tea houses to modern matcha cafes.",
        },
        "ja": {
            "title": "京都抹茶スイーツ - 宇治茶の本場で味わう極上の甘味",
            "category": "グルメ",
            "city": "京都",
            "description": "宇治茶の産地・京都で味わう極上の抹茶スイーツ。老舗茶房から最新カフェまで厳選紹介。",
        },
        "zh": {
            "title": "京都抹茶甜点 - 绿茶天堂",
            "category": "美食",
            "city": "京都",
            "description": "品味京都最优质的抹茶甜点，从百年茶屋到现代抹茶咖啡馆。",
        },
        "ko": {
            "title": "교토 말차 스위츠 - 녹차의 천국",
            "category": "음식",
            "city": "교토",
            "description": "우지차의 본고장 교토에서 맛보는 최고급 말차 스위츠. 전통 찻집부터 최신 카페까지.",
        },
        "es": {
            "title": "Dulces de Matcha en Kioto - El Paraíso del Té Verde",
            "category": "Gastronomía",
            "city": "Kioto",
            "description": "Disfruta de los mejores postres de matcha de Kioto, desde casas de té centenarias hasta cafeterías modernas.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Matcha_and_sweet_%288598729654%29.jpg/1280px-Matcha_and_sweet_%288598729654%29.jpg",
        "tags_en": ["matcha", "sweets", "kyoto", "green-tea"],
        "tags_ja": ["抹茶", "スイーツ", "京都", "宇治茶"],
        "tags_zh": ["抹茶", "甜点", "京都", "绿茶"],
        "tags_ko": ["말차", "스위츠", "교토", "녹차"],
        "tags_es": ["matcha", "dulces", "kioto", "té-verde"],
    },
    {
        "slug": "hokkaido-seafood",
        "en": {
            "title": "Hokkaido Seafood - Fresh from the Northern Seas",
            "category": "Food",
            "city": "Hokkaido",
            "description": "Feast on Hokkaido's legendary seafood: uni, crab, salmon, and scallops fresh from the cold northern waters.",
        },
        "ja": {
            "title": "北海道海鮮グルメ - 北の海の恵みを堪能",
            "category": "グルメ",
            "city": "北海道",
            "description": "ウニ、カニ、サーモン、ホタテ。北の冷たい海が育む絶品海鮮を楽しめる北海道グルメガイド。",
        },
        "zh": {
            "title": "北海道海鲜 - 来自北方海洋的新鲜美味",
            "category": "美食",
            "city": "北海道",
            "description": "品尝北海道传奇海鲜：海胆、螃蟹、三文鱼和扇贝，来自寒冷北方海域的新鲜食材。",
        },
        "ko": {
            "title": "홋카이도 해산물 - 북쪽 바다의 신선함",
            "category": "음식",
            "city": "홋카이도",
            "description": "성게, 게, 연어, 가리비. 차가운 북쪽 바다가 키운 홋카이도 해산물 가이드.",
        },
        "es": {
            "title": "Mariscos de Hokkaido - Frescos del Mar del Norte",
            "category": "Gastronomía",
            "city": "Hokkaido",
            "description": "Disfruta de los legendarios mariscos de Hokkaido: erizo de mar, cangrejo, salmón y vieiras frescos de las frías aguas del norte.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Kaisendon_in_Otaru.jpg/1280px-Kaisendon_in_Otaru.jpg",
        "tags_en": ["seafood", "hokkaido", "crab", "sushi"],
        "tags_ja": ["海鮮", "北海道", "カニ", "寿司"],
        "tags_zh": ["海鲜", "北海道", "螃蟹", "寿司"],
        "tags_ko": ["해산물", "홋카이도", "게", "스시"],
        "tags_es": ["mariscos", "hokkaido", "cangrejo", "sushi"],
    },
    {
        "slug": "fukuoka-yatai",
        "en": {
            "title": "Fukuoka Yatai - Nighttime Street Food Stalls",
            "category": "Food",
            "city": "Fukuoka",
            "description": "Experience Fukuoka's iconic yatai street food stalls along the river, serving the city's famous Hakata ramen and gyoza.",
        },
        "ja": {
            "title": "福岡屋台グルメ - 中洲の夜を楽しむ",
            "category": "グルメ",
            "city": "福岡",
            "description": "中洲の川沿いに並ぶ屋台で味わう博多ラーメンと餃子。福岡の夜の風物詩を紹介。",
        },
        "zh": {
            "title": "福冈屋台 - 夜间街头美食摊",
            "category": "美食",
            "city": "福冈",
            "description": "体验福冈标志性的屋台街头美食摊，沿河而设，供应著名的博多拉面和饺子。",
        },
        "ko": {
            "title": "후쿠오카 야타이 - 야간 길거리 음식 포장마차",
            "category": "음식",
            "city": "후쿠오카",
            "description": "강변에 늘어선 야타이에서 하카타 라멘과 교자를. 후쿠오카 밤의 풍경을 소개합니다.",
        },
        "es": {
            "title": "Yatai de Fukuoka - Puestos de Comida Callejera Nocturna",
            "category": "Gastronomía",
            "city": "Fukuoka",
            "description": "Vive la experiencia de los icónicos puestos yatai de Fukuoka a lo largo del río, sirviendo el famoso ramen Hakata y gyoza.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Yatai_in_Tenjin%2C_Fukuoka.jpg/1280px-Yatai_in_Tenjin%2C_Fukuoka.jpg",
        "tags_en": ["yatai", "street-food", "fukuoka", "hakata-ramen"],
        "tags_ja": ["屋台", "食べ歩き", "福岡", "博多ラーメン"],
        "tags_zh": ["屋台", "街头美食", "福冈", "博多拉面"],
        "tags_ko": ["야타이", "길거리음식", "후쿠오카", "하카타라멘"],
        "tags_es": ["yatai", "comida-callejera", "fukuoka", "ramen-hakata"],
    },
    {
        "slug": "hiroshima-okonomiyaki",
        "en": {
            "title": "Hiroshima Okonomiyaki - Layered Savory Pancake",
            "category": "Food",
            "city": "Hiroshima",
            "description": "Try Hiroshima-style okonomiyaki, the uniquely layered savory pancake with noodles, cabbage, and your choice of toppings.",
        },
        "ja": {
            "title": "広島お好み焼き - 重ね焼きの極意",
            "category": "グルメ",
            "city": "広島",
            "description": "そば入りの重ね焼きが特徴の広島風お好み焼き。地元民が愛する名店を厳選紹介。",
        },
        "zh": {
            "title": "广岛御好烧 - 层层叠叠的美味煎饼",
            "category": "美食",
            "city": "广岛",
            "description": "品尝广岛风御好烧，独特的层层叠加风格，搭配面条、卷心菜和您选择的配料。",
        },
        "ko": {
            "title": "히로시마 오코노미야키 - 겹겹이 쌓인 맛",
            "category": "음식",
            "city": "히로시마",
            "description": "면이 들어간 겹겹이 쌓는 스타일의 히로시마식 오코노미야키 명점을 소개합니다.",
        },
        "es": {
            "title": "Okonomiyaki de Hiroshima - Panqueque Salado por Capas",
            "category": "Gastronomía",
            "city": "Hiroshima",
            "description": "Prueba el okonomiyaki estilo Hiroshima, el panqueque salado con capas únicas de fideos, repollo y tus ingredientes favoritos.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Okonomiyaki_by_S_e_i_in_Hiroshima.jpg/1280px-Okonomiyaki_by_S_e_i_in_Hiroshima.jpg",
        "tags_en": ["okonomiyaki", "hiroshima", "pancake", "street-food"],
        "tags_ja": ["お好み焼き", "広島", "鉄板焼き", "グルメ"],
        "tags_zh": ["御好烧", "广岛", "煎饼", "街头美食"],
        "tags_ko": ["오코노미야키", "히로시마", "철판요리", "명물"],
        "tags_es": ["okonomiyaki", "hiroshima", "panqueque", "comida-callejera"],
    },
    {
        "slug": "nagoya-meshi",
        "en": {
            "title": "Nagoya Meshi - Complete Guide to Nagoya Cuisine",
            "category": "Food",
            "city": "Nagoya",
            "description": "Explore Nagoya's unique food culture: miso katsu, hitsumabushi eel, tebasaki chicken wings, and more.",
        },
        "ja": {
            "title": "名古屋メシ完全ガイド - 味噌カツからひつまぶしまで",
            "category": "グルメ",
            "city": "名古屋",
            "description": "味噌カツ、ひつまぶし、手羽先、台湾ラーメン。独自の食文化が花開く名古屋メシを完全網羅。",
        },
        "zh": {
            "title": "名古屋美食完全指南",
            "category": "美食",
            "city": "名古屋",
            "description": "探索名古屋独特的美食文化：味噌猪排、鳗鱼三吃、手羽先鸡翅等。",
        },
        "ko": {
            "title": "나고야 메시 - 나고야 음식 완전 가이드",
            "category": "음식",
            "city": "나고야",
            "description": "미소카쓰, 히쓰마부시, 데바사키. 독특한 식문화의 나고야 음식을 완전 가이드.",
        },
        "es": {
            "title": "Nagoya Meshi - Guía Completa de la Cocina de Nagoya",
            "category": "Gastronomía",
            "city": "Nagoya",
            "description": "Explora la cultura gastronómica única de Nagoya: miso katsu, anguila hitsumabushi, alitas tebasaki y más.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Hitsumabushi_by_yrkhang_in_Nagoya%2C_Aichi.jpg/1280px-Hitsumabushi_by_yrkhang_in_Nagoya%2C_Aichi.jpg",
        "tags_en": ["nagoya", "miso-katsu", "hitsumabushi", "food-guide"],
        "tags_ja": ["名古屋", "味噌カツ", "ひつまぶし", "グルメガイド"],
        "tags_zh": ["名古屋", "味噌猪排", "鳗鱼三吃", "美食指南"],
        "tags_ko": ["나고야", "미소카쓰", "히쓰마부시", "음식가이드"],
        "tags_es": ["nagoya", "miso-katsu", "hitsumabushi", "guía-gastronómica"],
    },
    {
        "slug": "wagyu-guide",
        "en": {
            "title": "Wagyu Beef Guide - How to Enjoy Japan's Finest Beef",
            "category": "Food",
            "city": "Various",
            "description": "Everything you need to know about wagyu beef: Kobe, Matsusaka, and Omi beef explained, plus where and how to eat it.",
        },
        "ja": {
            "title": "和牛の楽しみ方ガイド - 神戸牛・松阪牛・近江牛",
            "category": "グルメ",
            "city": "全国",
            "description": "神戸牛、松阪牛、近江牛の三大和牛を徹底解説。焼肉、すき焼き、しゃぶしゃぶの楽しみ方も。",
        },
        "zh": {
            "title": "和牛指南 - 如何享用日本顶级牛肉",
            "category": "美食",
            "city": "日本各地",
            "description": "关于和牛的一切：神户牛、松阪牛、近江牛详解，以及在哪里和如何品尝。",
        },
        "ko": {
            "title": "와규 가이드 - 일본 최고급 소고기 즐기는 법",
            "category": "음식",
            "city": "일본 각지",
            "description": "고베규, 마쓰사카규, 오미규의 3대 와규 완전 해설. 야키니쿠, 스키야키, 샤브샤브까지.",
        },
        "es": {
            "title": "Guía del Wagyu - Cómo Disfrutar la Mejor Carne de Japón",
            "category": "Gastronomía",
            "city": "Varios",
            "description": "Todo lo que necesitas saber sobre la carne wagyu: Kobe, Matsusaka y Omi explicados, además de dónde y cómo comerla.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Matsusaka_beef.jpg/1280px-Matsusaka_beef.jpg",
        "tags_en": ["wagyu", "kobe-beef", "food", "luxury"],
        "tags_ja": ["和牛", "神戸牛", "グルメ", "高級"],
        "tags_zh": ["和牛", "神户牛", "美食", "高级"],
        "tags_ko": ["와규", "고베규", "음식", "고급"],
        "tags_es": ["wagyu", "carne-kobe", "gastronomía", "lujo"],
    },
    {
        "slug": "sushi-guide",
        "en": {
            "title": "Sushi Etiquette Guide - How to Eat Sushi Like a Local",
            "category": "Food",
            "city": "Various",
            "description": "Master the art of eating sushi: etiquette, ordering tips, and the best sushi experiences from conveyor belts to Michelin stars.",
        },
        "ja": {
            "title": "寿司の食べ方ガイド - 通が教えるマナーと楽しみ方",
            "category": "グルメ",
            "city": "全国",
            "description": "回転寿司から高級寿司まで。知っておきたい寿司のマナーと、もっと楽しむためのコツを紹介。",
        },
        "zh": {
            "title": "寿司礼仪指南 - 像当地人一样吃寿司",
            "category": "美食",
            "city": "日本各地",
            "description": "掌握吃寿司的艺术：礼仪、点餐技巧，从回转寿司到米其林星级的最佳体验。",
        },
        "ko": {
            "title": "스시 에티켓 가이드 - 현지인처럼 스시 먹기",
            "category": "음식",
            "city": "일본 각지",
            "description": "회전초밥부터 고급 스시까지. 알아두면 좋은 스시 매너와 즐기는 법을 소개합니다.",
        },
        "es": {
            "title": "Guía de Etiqueta del Sushi - Cómo Comer Sushi Como un Local",
            "category": "Gastronomía",
            "city": "Varios",
            "description": "Domina el arte de comer sushi: etiqueta, consejos para pedir y las mejores experiencias, desde cintas transportadoras hasta estrellas Michelin.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Sushi_platter.jpg/1280px-Sushi_platter.jpg",
        "tags_en": ["sushi", "etiquette", "food", "guide"],
        "tags_ja": ["寿司", "マナー", "グルメ", "ガイド"],
        "tags_zh": ["寿司", "礼仪", "美食", "指南"],
        "tags_ko": ["스시", "매너", "음식", "가이드"],
        "tags_es": ["sushi", "etiqueta", "gastronomía", "guía"],
    },
    {
        "slug": "sake-guide",
        "en": {
            "title": "Japanese Sake Guide - From Beginner to Connoisseur",
            "category": "Food",
            "city": "Various",
            "description": "Your complete guide to Japanese sake: types, tasting notes, food pairings, and the best sake breweries to visit.",
        },
        "ja": {
            "title": "日本酒入門 - 初心者から通まで楽しむガイド",
            "category": "グルメ",
            "city": "全国",
            "description": "純米、吟醸、大吟醸の違いから、料理とのペアリング、おすすめ酒蔵巡りまで日本酒を完全ガイド。",
        },
        "zh": {
            "title": "日本清酒指南 - 从入门到鉴赏家",
            "category": "美食",
            "city": "日本各地",
            "description": "日本清酒完全指南：种类、品鉴笔记、美食搭配和最佳酒厂参观。",
        },
        "ko": {
            "title": "일본주 가이드 - 입문자부터 마니아까지",
            "category": "음식",
            "city": "일본 각지",
            "description": "준마이, 긴조, 다이긴조의 차이부터 음식 페어링, 양조장 투어까지 일본주를 완전 가이드.",
        },
        "es": {
            "title": "Guía del Sake Japonés - De Principiante a Conocedor",
            "category": "Gastronomía",
            "city": "Varios",
            "description": "Tu guía completa del sake japonés: tipos, notas de cata, maridajes y las mejores destilerías para visitar.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Sake_barrels_offering_at_Meiji_Shrine.jpg/1280px-Sake_barrels_offering_at_Meiji_Shrine.jpg",
        "tags_en": ["sake", "alcohol", "brewery", "tasting"],
        "tags_ja": ["日本酒", "酒", "酒蔵", "試飲"],
        "tags_zh": ["清酒", "酒", "酒厂", "品酒"],
        "tags_ko": ["일본주", "술", "양조장", "시음"],
        "tags_es": ["sake", "alcohol", "destilería", "degustación"],
    },
    # ==================== CITIES (21-30) ====================
    {
        "slug": "tokyo-guide",
        "en": {
            "title": "Tokyo Complete Guide - The Ultimate City Experience",
            "category": "Cities",
            "city": "Tokyo",
            "description": "Your complete guide to Tokyo, from neon-lit Shibuya to traditional Asakusa, covering all must-see neighborhoods and attractions.",
        },
        "ja": {
            "title": "東京完全ガイド - 世界一の大都市を遊び尽くす",
            "category": "都市",
            "city": "東京",
            "description": "渋谷のネオンから浅草の下町情緒まで。全エリアを網羅した東京観光の完全ガイド。",
        },
        "zh": {
            "title": "东京完全指南 - 终极城市体验",
            "category": "城市",
            "city": "东京",
            "description": "东京完全指南，从霓虹闪烁的涩谷到传统的浅草，涵盖所有必看街区和景点。",
        },
        "ko": {
            "title": "도쿄 완전 가이드 - 최고의 도시 체험",
            "category": "도시",
            "city": "도쿄",
            "description": "시부야의 네온부터 아사쿠사의 정취까지. 전 에리어를 망라한 도쿄 관광 완전 가이드.",
        },
        "es": {
            "title": "Guía Completa de Tokio - La Experiencia Urbana Definitiva",
            "category": "Ciudades",
            "city": "Tokio",
            "description": "Tu guía completa de Tokio, desde el neón de Shibuya hasta el tradicional Asakusa, cubriendo todos los barrios y atracciones imprescindibles.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Skyscrapers_of_Shinjuku_2009_January.jpg/1280px-Skyscrapers_of_Shinjuku_2009_January.jpg",
        "tags_en": ["tokyo", "city-guide", "shibuya", "shinjuku"],
        "tags_ja": ["東京", "都市ガイド", "渋谷", "新宿"],
        "tags_zh": ["东京", "城市指南", "涩谷", "新宿"],
        "tags_ko": ["도쿄", "도시가이드", "시부야", "신주쿠"],
        "tags_es": ["tokio", "guía-urbana", "shibuya", "shinjuku"],
    },
    {
        "slug": "kyoto-guide",
        "en": {
            "title": "Kyoto Complete Guide - Ancient Capital of Japan",
            "category": "Cities",
            "city": "Kyoto",
            "description": "Explore Kyoto, Japan's ancient capital, with its 2,000+ temples, traditional geisha district, and exquisite gardens.",
        },
        "ja": {
            "title": "京都完全ガイド - 千年の都を歩く",
            "category": "都市",
            "city": "京都",
            "description": "2000以上の寺社仏閣、花街の風情、美しい庭園。千年の歴史を誇る京都の魅力を完全ガイド。",
        },
        "zh": {
            "title": "京都完全指南 - 日本的古都",
            "category": "城市",
            "city": "京都",
            "description": "探索京都，日本古都，拥有2000多座寺庙、传统艺伎区和精致的庭园。",
        },
        "ko": {
            "title": "교토 완전 가이드 - 일본의 고도",
            "category": "도시",
            "city": "교토",
            "description": "2000개 이상의 사찰, 게이샤 거리, 아름다운 정원. 천년 고도 교토의 매력을 완전 가이드.",
        },
        "es": {
            "title": "Guía Completa de Kioto - Antigua Capital de Japón",
            "category": "Ciudades",
            "city": "Kioto",
            "description": "Explora Kioto, la antigua capital de Japón, con sus más de 2,000 templos, el tradicional distrito geisha y exquisitos jardines.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Higashiyama%2C_Kyoto%2C_Japan_%2848835836646%29.jpg/1280px-Higashiyama%2C_Kyoto%2C_Japan_%2848835836646%29.jpg",
        "tags_en": ["kyoto", "ancient-capital", "geisha", "temples"],
        "tags_ja": ["京都", "古都", "舞妓", "寺社"],
        "tags_zh": ["京都", "古都", "艺伎", "寺庙"],
        "tags_ko": ["교토", "고도", "게이샤", "사찰"],
        "tags_es": ["kioto", "antigua-capital", "geisha", "templos"],
    },
    {
        "slug": "osaka-guide",
        "en": {
            "title": "Osaka Complete Guide - Japan's Kitchen and Entertainment Hub",
            "category": "Cities",
            "city": "Osaka",
            "description": "Discover Osaka, the city of food and fun, from Dotonbori's neon signs to Osaka Castle and the vibrant nightlife.",
        },
        "ja": {
            "title": "大阪完全ガイド - 食い倒れの街を楽しむ",
            "category": "都市",
            "city": "大阪",
            "description": "道頓堀のネオン、大阪城、新世界の串カツ。食い倒れの街・大阪の魅力を完全ガイド。",
        },
        "zh": {
            "title": "大阪完全指南 - 日本的厨房和娱乐中心",
            "category": "城市",
            "city": "大阪",
            "description": "发现大阪，美食和娱乐之都，从道顿堀的霓虹灯到大阪城和充满活力的夜生活。",
        },
        "ko": {
            "title": "오사카 완전 가이드 - 일본의 부엌과 놀이터",
            "category": "도시",
            "city": "오사카",
            "description": "도톤보리의 네온, 오사카성, 신세카이의 쿠시카쓰. 먹거리 천국 오사카를 완전 가이드.",
        },
        "es": {
            "title": "Guía Completa de Osaka - La Cocina y Centro de Entretenimiento de Japón",
            "category": "Ciudades",
            "city": "Osaka",
            "description": "Descubre Osaka, la ciudad de la comida y la diversión, desde los neones de Dotonbori hasta el Castillo de Osaka y la vibrante vida nocturna.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Dotonbori_at_night%2C_25th_May_2016_%282%29.jpg/1280px-Dotonbori_at_night%2C_25th_May_2016_%282%29.jpg",
        "tags_en": ["osaka", "dotonbori", "street-food", "nightlife"],
        "tags_ja": ["大阪", "道頓堀", "食べ歩き", "ナイトライフ"],
        "tags_zh": ["大阪", "道顿堀", "街头美食", "夜生活"],
        "tags_ko": ["오사카", "도톤보리", "길거리음식", "야경"],
        "tags_es": ["osaka", "dotonbori", "comida-callejera", "vida-nocturna"],
    },
    {
        "slug": "sapporo-guide",
        "en": {
            "title": "Sapporo Guide - Gateway to Hokkaido",
            "category": "Cities",
            "city": "Sapporo",
            "description": "Explore Sapporo, Hokkaido's capital, famous for its beer, snow festival, and proximity to world-class ski resorts.",
        },
        "ja": {
            "title": "札幌ガイド - 北海道の玄関口",
            "category": "都市",
            "city": "札幌",
            "description": "ビール、雪まつり、ジンギスカン。北海道の首都・札幌の魅力とスキーリゾートへのアクセスを紹介。",
        },
        "zh": {
            "title": "札幌指南 - 北海道的门户",
            "category": "城市",
            "city": "札幌",
            "description": "探索札幌，北海道首府，以啤酒、雪祭和世界级滑雪胜地闻名。",
        },
        "ko": {
            "title": "삿포로 가이드 - 홋카이도의 관문",
            "category": "도시",
            "city": "삿포로",
            "description": "맥주, 눈 축제, 징기스칸. 홋카이도의 수도 삿포로와 스키 리조트를 소개합니다.",
        },
        "es": {
            "title": "Guía de Sapporo - Puerta de Entrada a Hokkaido",
            "category": "Ciudades",
            "city": "Sapporo",
            "description": "Explora Sapporo, capital de Hokkaido, famosa por su cerveza, festival de nieve y cercanía a estaciones de esquí de clase mundial.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Sapporo_Station_Square_from_JR_Tower.jpg/1280px-Sapporo_Station_Square_from_JR_Tower.jpg",
        "tags_en": ["sapporo", "hokkaido", "beer", "snow-festival"],
        "tags_ja": ["札幌", "北海道", "ビール", "雪まつり"],
        "tags_zh": ["札幌", "北海道", "啤酒", "雪祭"],
        "tags_ko": ["삿포로", "홋카이도", "맥주", "눈축제"],
        "tags_es": ["sapporo", "hokkaido", "cerveza", "festival-de-nieve"],
    },
    {
        "slug": "okinawa-guide",
        "en": {
            "title": "Okinawa Guide - Japan's Tropical Paradise",
            "category": "Cities",
            "city": "Okinawa",
            "description": "Discover Okinawa, Japan's tropical island chain with crystal-clear beaches, unique Ryukyu culture, and world-class diving.",
        },
        "ja": {
            "title": "沖縄ガイド - 日本の南国リゾート",
            "category": "都市",
            "city": "沖縄",
            "description": "透明度抜群のビーチ、琉球文化、世界屈指のダイビングスポット。沖縄の魅力を完全ガイド。",
        },
        "zh": {
            "title": "冲绳指南 - 日本的热带天堂",
            "category": "城市",
            "city": "冲绳",
            "description": "发现冲绳，日本的热带岛链，拥有清澈的海滩、独特的琉球文化和世界级潜水。",
        },
        "ko": {
            "title": "오키나와 가이드 - 일본의 열대 낙원",
            "category": "도시",
            "city": "오키나와",
            "description": "투명한 바다, 류큐 문화, 세계적인 다이빙 스팟. 오키나와의 매력을 완전 가이드.",
        },
        "es": {
            "title": "Guía de Okinawa - El Paraíso Tropical de Japón",
            "category": "Ciudades",
            "city": "Okinawa",
            "description": "Descubre Okinawa, la cadena de islas tropicales de Japón con playas cristalinas, cultura Ryukyu única y buceo de clase mundial.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Kerama_Islands_National_Park_Zamami.jpg/1280px-Kerama_Islands_National_Park_Zamami.jpg",
        "tags_en": ["okinawa", "beach", "tropical", "diving"],
        "tags_ja": ["沖縄", "ビーチ", "南国", "ダイビング"],
        "tags_zh": ["冲绳", "海滩", "热带", "潜水"],
        "tags_ko": ["오키나와", "해변", "열대", "다이빙"],
        "tags_es": ["okinawa", "playa", "tropical", "buceo"],
    },
    {
        "slug": "hiroshima-guide",
        "en": {
            "title": "Hiroshima Guide - Peace, History, and Island Beauty",
            "category": "Cities",
            "city": "Hiroshima",
            "description": "Visit Hiroshima for its Peace Memorial, vibrant food scene, and easy access to the beautiful Miyajima Island.",
        },
        "ja": {
            "title": "広島ガイド - 平和と歴史、そして島の美しさ",
            "category": "都市",
            "city": "広島",
            "description": "平和記念公園、お好み焼き、そして宮島へのアクセス。広島の見どころを完全ガイド。",
        },
        "zh": {
            "title": "广岛指南 - 和平、历史与岛屿之美",
            "category": "城市",
            "city": "广岛",
            "description": "参观广岛的和平纪念馆、充满活力的美食场景，以及美丽的宫岛。",
        },
        "ko": {
            "title": "히로시마 가이드 - 평화, 역사, 그리고 섬의 아름다움",
            "category": "도시",
            "city": "히로시마",
            "description": "평화기념공원, 오코노미야키, 미야지마. 히로시마의 볼거리를 완전 가이드.",
        },
        "es": {
            "title": "Guía de Hiroshima - Paz, Historia y Belleza Insular",
            "category": "Ciudades",
            "city": "Hiroshima",
            "description": "Visita Hiroshima por su Memorial de la Paz, vibrante escena gastronómica y fácil acceso a la hermosa Isla Miyajima.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Genbaku_Dome04-r.jpg/1280px-Genbaku_Dome04-r.jpg",
        "tags_en": ["hiroshima", "peace", "miyajima", "history"],
        "tags_ja": ["広島", "平和", "宮島", "歴史"],
        "tags_zh": ["广岛", "和平", "宫岛", "历史"],
        "tags_ko": ["히로시마", "평화", "미야지마", "역사"],
        "tags_es": ["hiroshima", "paz", "miyajima", "historia"],
    },
    {
        "slug": "nara-guide",
        "en": {
            "title": "Nara Guide - City of Deer and Ancient Temples",
            "category": "Cities",
            "city": "Nara",
            "description": "Explore Nara, home to friendly wild deer, massive Buddhist temples, and Japan's earliest historical treasures.",
        },
        "ja": {
            "title": "奈良ガイド - 鹿と古寺の都",
            "category": "都市",
            "city": "奈良",
            "description": "人懐っこい鹿、巨大な仏像、日本最古の歴史遺産。奈良の魅力を完全ガイド。",
        },
        "zh": {
            "title": "奈良指南 - 鹿与古寺之城",
            "category": "城市",
            "city": "奈良",
            "description": "探索奈良，拥有友好的野生鹿、宏伟的佛教寺庙和日本最早的历史珍宝。",
        },
        "ko": {
            "title": "나라 가이드 - 사슴과 고대 사찰의 도시",
            "category": "도시",
            "city": "나라",
            "description": "사람을 좋아하는 사슴, 거대한 불상, 일본 최고의 역사유산. 나라의 매력을 완전 가이드.",
        },
        "es": {
            "title": "Guía de Nara - Ciudad de Ciervos y Templos Antiguos",
            "category": "Ciudades",
            "city": "Nara",
            "description": "Explora Nara, hogar de ciervos silvestres amigables, enormes templos budistas y los tesoros históricos más antiguos de Japón.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Nara_Park_Wakakusa-yama_3.jpg/1280px-Nara_Park_Wakakusa-yama_3.jpg",
        "tags_en": ["nara", "deer", "temples", "ancient"],
        "tags_ja": ["奈良", "鹿", "寺院", "古代"],
        "tags_zh": ["奈良", "鹿", "寺庙", "古代"],
        "tags_ko": ["나라", "사슴", "사찰", "고대"],
        "tags_es": ["nara", "ciervos", "templos", "antiguo"],
    },
    {
        "slug": "kanazawa-guide",
        "en": {
            "title": "Kanazawa Guide - Japan's Hidden Cultural Gem",
            "category": "Cities",
            "city": "Kanazawa",
            "description": "Discover Kanazawa, a city of samurai districts, geisha quarters, and Kenrokuen, one of Japan's three great gardens.",
        },
        "ja": {
            "title": "金沢ガイド - 北陸の小京都",
            "category": "都市",
            "city": "金沢",
            "description": "武家屋敷、ひがし茶屋街、兼六園。加賀百万石の城下町・金沢の魅力を完全ガイド。",
        },
        "zh": {
            "title": "金�的指南 - 日本隐藏的文化瑰宝",
            "category": "城市",
            "city": "金泽",
            "description": "发现金泽，一座拥有武士区、艺伎街和兼六园的城市，兼六园是日本三大名园之一。",
        },
        "ko": {
            "title": "가나자와 가이드 - 일본의 숨겨진 문화 보석",
            "category": "도시",
            "city": "가나자와",
            "description": "사무라이 거리, 게이샤 골목, 겐로쿠엔. 가가 백만석의 성하마을 가나자와를 완전 가이드.",
        },
        "es": {
            "title": "Guía de Kanazawa - La Joya Cultural Oculta de Japón",
            "category": "Ciudades",
            "city": "Kanazawa",
            "description": "Descubre Kanazawa, una ciudad de distritos samurái, barrios geisha y Kenrokuen, uno de los tres grandes jardines de Japón.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Kenrokuen_Kotoji-toro_Panorama.jpg/1280px-Kenrokuen_Kotoji-toro_Panorama.jpg",
        "tags_en": ["kanazawa", "garden", "samurai", "geisha"],
        "tags_ja": ["金沢", "庭園", "武士", "芸妓"],
        "tags_zh": ["金泽", "庭园", "武士", "艺伎"],
        "tags_ko": ["가나자와", "정원", "사무라이", "게이샤"],
        "tags_es": ["kanazawa", "jardín", "samurái", "geisha"],
    },
    {
        "slug": "kamakura-guide",
        "en": {
            "title": "Kamakura Guide - Seaside Temple Town Near Tokyo",
            "category": "Cities",
            "city": "Kamakura",
            "description": "Explore Kamakura, a charming seaside town just an hour from Tokyo, known for its Great Buddha and beautiful temples.",
        },
        "ja": {
            "title": "鎌倉ガイド - 古都と海のまち",
            "category": "都市",
            "city": "鎌倉",
            "description": "大仏、鶴岡八幡宮、そして湘南の海。東京から1時間で行ける古都・鎌倉の魅力を紹介。",
        },
        "zh": {
            "title": "镰仓指南 - 东京附近的海边寺庙小镇",
            "category": "城市",
            "city": "镰仓",
            "description": "探索镰仓，距东京仅一小时的迷人海滨小镇，以大佛和美丽的寺庙闻名。",
        },
        "ko": {
            "title": "가마쿠라 가이드 - 도쿄 근교의 해변 사찰 마을",
            "category": "도시",
            "city": "가마쿠라",
            "description": "대불, 쓰루가오카하치만구, 쇼난 해변. 도쿄에서 1시간 거리의 고도 가마쿠라를 소개합니다.",
        },
        "es": {
            "title": "Guía de Kamakura - Pueblo Costero de Templos Cerca de Tokio",
            "category": "Ciudades",
            "city": "Kamakura",
            "description": "Explora Kamakura, un encantador pueblo costero a solo una hora de Tokio, conocido por su Gran Buda y hermosos templos.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Kamakura_Budda_Daibutsu_front_1885.jpg/1280px-Kamakura_Budda_Daibutsu_front_1885.jpg",
        "tags_en": ["kamakura", "great-buddha", "seaside", "day-trip"],
        "tags_ja": ["鎌倉", "大仏", "海", "日帰り"],
        "tags_zh": ["镰仓", "大佛", "海边", "一日游"],
        "tags_ko": ["가마쿠라", "대불", "해변", "당일치기"],
        "tags_es": ["kamakura", "gran-buda", "costero", "excursión"],
    },
    {
        "slug": "hakone-guide",
        "en": {
            "title": "Hakone Guide - Hot Springs with Mount Fuji Views",
            "category": "Cities",
            "city": "Hakone",
            "description": "Experience Hakone, a mountain resort town known for its hot springs, stunning Mount Fuji views, and art museums.",
        },
        "ja": {
            "title": "箱根ガイド - 富士山を望む温泉郷",
            "category": "都市",
            "city": "箱根",
            "description": "温泉、富士山の絶景、美術館。東京から気軽に行ける箱根の魅力を完全ガイド。",
        },
        "zh": {
            "title": "箱根指南 - 富士山景的温泉小镇",
            "category": "城市",
            "city": "箱根",
            "description": "体验箱根，以温泉、壮观的富士山景色和艺术博物馆闻名的山间度假小镇。",
        },
        "ko": {
            "title": "하코네 가이드 - 후지산이 보이는 온천 마을",
            "category": "도시",
            "city": "하코네",
            "description": "온천, 후지산 절경, 미술관. 도쿄에서 부담 없이 갈 수 있는 하코네의 매력을 완전 가이드.",
        },
        "es": {
            "title": "Guía de Hakone - Aguas Termales con Vistas al Monte Fuji",
            "category": "Ciudades",
            "city": "Hakone",
            "description": "Vive Hakone, un pueblo de montaña conocido por sus aguas termales, impresionantes vistas del Monte Fuji y museos de arte.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Lake_Ashi_from_Hakone_Ropeway.jpg/1280px-Lake_Ashi_from_Hakone_Ropeway.jpg",
        "tags_en": ["hakone", "hot-spring", "mount-fuji", "art-museum"],
        "tags_ja": ["箱根", "温泉", "富士山", "美術館"],
        "tags_zh": ["箱根", "温泉", "富士山", "美术馆"],
        "tags_ko": ["하코네", "온천", "후지산", "미술관"],
        "tags_es": ["hakone", "aguas-termales", "monte-fuji", "museo-de-arte"],
    },
    # ==================== CULTURE (31-40) ====================
    {
        "slug": "onsen-guide",
        "en": {
            "title": "Japanese Onsen Guide - Hot Spring Bathing Etiquette",
            "category": "Culture",
            "city": "Various",
            "description": "Everything you need to know about Japanese hot springs: etiquette, tattoo policies, types of onsen, and the best onsen towns.",
        },
        "ja": {
            "title": "温泉入浴ガイド - マナーと楽しみ方",
            "category": "文化",
            "city": "全国",
            "description": "入浴マナー、タトゥーポリシー、温泉の種類、おすすめ温泉地。温泉を100%楽しむためのガイド。",
        },
        "zh": {
            "title": "日本温泉指南 - 泡汤礼仪",
            "category": "文化",
            "city": "日本各地",
            "description": "关于日本温泉的一切：礼仪、纹身政策、温泉类型和最佳温泉小镇。",
        },
        "ko": {
            "title": "일본 온천 가이드 - 입욕 에티켓",
            "category": "문화",
            "city": "일본 각지",
            "description": "입욕 매너, 타투 정책, 온천 종류, 추천 온천지. 온천을 100% 즐기기 위한 가이드.",
        },
        "es": {
            "title": "Guía de Onsen Japonés - Etiqueta del Baño Termal",
            "category": "Cultura",
            "city": "Varios",
            "description": "Todo lo que necesitas saber sobre las aguas termales japonesas: etiqueta, políticas de tatuajes, tipos de onsen y los mejores pueblos termales.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Kusatsu_Onsen_01.jpg/1280px-Kusatsu_Onsen_01.jpg",
        "tags_en": ["onsen", "hot-spring", "etiquette", "culture"],
        "tags_ja": ["温泉", "入浴", "マナー", "文化"],
        "tags_zh": ["温泉", "泡汤", "礼仪", "文化"],
        "tags_ko": ["온천", "입욕", "매너", "문화"],
        "tags_es": ["onsen", "aguas-termales", "etiqueta", "cultura"],
    },
    {
        "slug": "kimono-experience",
        "en": {
            "title": "Kimono Experience - Where to Wear Traditional Japanese Clothing",
            "category": "Culture",
            "city": "Various",
            "description": "Rent and wear a beautiful kimono or yukata while exploring Japan's most photogenic locations.",
        },
        "ja": {
            "title": "着物体験 - 和装で巡る日本の名所",
            "category": "文化",
            "city": "全国",
            "description": "着物や浴衣をレンタルして、日本の美しい名所を和装で散策。おすすめの着物体験スポットを紹介。",
        },
        "zh": {
            "title": "和服体验 - 在哪里穿日本传统服装",
            "category": "文化",
            "city": "日本各地",
            "description": "租一件美丽的和服或浴衣，穿着它探索日本最上镜的地点。",
        },
        "ko": {
            "title": "기모노 체험 - 일본 전통 의상을 입고 걷기",
            "category": "문화",
            "city": "일본 각지",
            "description": "기모노나 유카타를 대여하여 일본의 아름다운 명소를 산책. 추천 기모노 체험 스팟을 소개합니다.",
        },
        "es": {
            "title": "Experiencia Kimono - Dónde Vestir Ropa Tradicional Japonesa",
            "category": "Cultura",
            "city": "Varios",
            "description": "Alquila y viste un hermoso kimono o yukata mientras exploras los lugares más fotogénicos de Japón.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Kimono_lady_at_Kiyomizu-dera%2C_Kyoto.jpg/800px-Kimono_lady_at_Kiyomizu-dera%2C_Kyoto.jpg",
        "tags_en": ["kimono", "yukata", "culture", "experience"],
        "tags_ja": ["着物", "浴衣", "文化", "体験"],
        "tags_zh": ["和服", "浴衣", "文化", "体验"],
        "tags_ko": ["기모노", "유카타", "문화", "체험"],
        "tags_es": ["kimono", "yukata", "cultura", "experiencia"],
    },
    {
        "slug": "tea-ceremony",
        "en": {
            "title": "Tea Ceremony Experience - The Way of Tea",
            "category": "Culture",
            "city": "Various",
            "description": "Learn about the Japanese tea ceremony, its history, philosophy, and where to enjoy an authentic matcha experience.",
        },
        "ja": {
            "title": "茶道体験 - 一期一会のおもてなし",
            "category": "文化",
            "city": "全国",
            "description": "茶道の歴史、哲学、そして本格的な抹茶体験ができるスポットを紹介。一期一会の精神を体感しよう。",
        },
        "zh": {
            "title": "茶道体验 - 茶之道",
            "category": "文化",
            "city": "日本各地",
            "description": "了解日本茶道，其历史、哲学，以及在哪里享受正宗的抹茶体验。",
        },
        "ko": {
            "title": "다도 체험 - 차의 길",
            "category": "문화",
            "city": "일본 각지",
            "description": "다도의 역사, 철학, 그리고 정통 말차 체험을 할 수 있는 곳을 소개합니다.",
        },
        "es": {
            "title": "Experiencia de Ceremonia del Té - El Camino del Té",
            "category": "Cultura",
            "city": "Varios",
            "description": "Aprende sobre la ceremonia del té japonesa, su historia, filosofía y dónde disfrutar de una experiencia auténtica con matcha.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Tea_ceremony_performing_2.jpg/1280px-Tea_ceremony_performing_2.jpg",
        "tags_en": ["tea-ceremony", "matcha", "culture", "zen"],
        "tags_ja": ["茶道", "抹茶", "文化", "禅"],
        "tags_zh": ["茶道", "抹茶", "文化", "禅"],
        "tags_ko": ["다도", "말차", "문화", "선"],
        "tags_es": ["ceremonia-del-té", "matcha", "cultura", "zen"],
    },
    {
        "slug": "japanese-festivals",
        "en": {
            "title": "Japanese Festivals Guide - Matsuri Throughout the Year",
            "category": "Culture",
            "city": "Various",
            "description": "A seasonal guide to Japan's most spectacular festivals, from cherry blossom celebrations to fiery summer matsuri.",
        },
        "ja": {
            "title": "日本の祭りガイド - 四季を彩る祭り",
            "category": "文化",
            "city": "全国",
            "description": "花見から夏祭り、秋の収穫祭まで。日本全国の壮大な祭りを季節ごとに紹介。",
        },
        "zh": {
            "title": "日本节日指南 - 全年祭典",
            "category": "文化",
            "city": "日本各地",
            "description": "日本最壮观节日的季节性指南，从樱花庆典到热火朝天的夏季祭典。",
        },
        "ko": {
            "title": "일본 축제 가이드 - 사계절의 마쓰리",
            "category": "문화",
            "city": "일본 각지",
            "description": "벚꽃놀이부터 여름 마쓰리, 가을 수확제까지. 일본 전국의 장대한 축제를 계절별로 소개.",
        },
        "es": {
            "title": "Guía de Festivales Japoneses - Matsuri Durante Todo el Año",
            "category": "Cultura",
            "city": "Varios",
            "description": "Una guía estacional de los festivales más espectaculares de Japón, desde celebraciones de cerezos en flor hasta los ardientes matsuri de verano.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Gion_Matsuri_2017-7.jpg/1280px-Gion_Matsuri_2017-7.jpg",
        "tags_en": ["festival", "matsuri", "culture", "seasonal"],
        "tags_ja": ["祭り", "まつり", "文化", "季節"],
        "tags_zh": ["节日", "祭典", "文化", "季节"],
        "tags_ko": ["축제", "마쓰리", "문화", "계절"],
        "tags_es": ["festival", "matsuri", "cultura", "estacional"],
    },
    {
        "slug": "sumo-guide",
        "en": {
            "title": "Sumo Wrestling Guide - How to Watch Japan's National Sport",
            "category": "Culture",
            "city": "Tokyo",
            "description": "Your complete guide to sumo: tournament schedules, how to buy tickets, rules, and the best ways to experience sumo in Japan.",
        },
        "ja": {
            "title": "相撲観戦ガイド - 国技を楽しむ",
            "category": "文化",
            "city": "東京",
            "description": "本場所のスケジュール、チケットの買い方、ルール解説。相撲を120%楽しむための完全ガイド。",
        },
        "zh": {
            "title": "相扑观赛指南 - 如何观看日本国技",
            "category": "文化",
            "city": "东京",
            "description": "相扑完全指南：锦标赛日程、购票方法、规则和在日本体验相扑的最佳方式。",
        },
        "ko": {
            "title": "스모 관전 가이드 - 일본 국기를 즐기는 법",
            "category": "문화",
            "city": "도쿄",
            "description": "혼바쇼 스케줄, 티켓 구매법, 규칙 해설. 스모를 120% 즐기기 위한 완전 가이드.",
        },
        "es": {
            "title": "Guía de Sumo - Cómo Ver el Deporte Nacional de Japón",
            "category": "Cultura",
            "city": "Tokio",
            "description": "Tu guía completa del sumo: calendarios de torneos, cómo comprar entradas, reglas y las mejores formas de experimentar el sumo en Japón.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Asashoryu_fight_Jan08.JPG/1280px-Asashoryu_fight_Jan08.JPG",
        "tags_en": ["sumo", "sport", "tokyo", "tradition"],
        "tags_ja": ["相撲", "スポーツ", "東京", "伝統"],
        "tags_zh": ["相扑", "运动", "东京", "传统"],
        "tags_ko": ["스모", "스포츠", "도쿄", "전통"],
        "tags_es": ["sumo", "deporte", "tokio", "tradición"],
    },
    {
        "slug": "anime-pilgrimage",
        "en": {
            "title": "Anime Pilgrimage Guide - Visit Real-Life Anime Locations",
            "category": "Culture",
            "city": "Various",
            "description": "Visit the real-world locations that inspired your favorite anime, from Your Name's Suga Shrine to Spirited Away's bathhouse.",
        },
        "ja": {
            "title": "アニメ聖地巡礼ガイド - 作品の舞台を訪ねる",
            "category": "文化",
            "city": "全国",
            "description": "『君の名は。』の須賀神社から『千と千尋の神隠し』のモデル地まで。アニメ聖地巡礼の完全ガイド。",
        },
        "zh": {
            "title": "动漫圣地巡礼指南 - 访问真实动漫场景",
            "category": "文化",
            "city": "日本各地",
            "description": "访问启发你最爱动漫的真实地点，从《你的名字》的须贺神社到《千与千寻》的浴场。",
        },
        "ko": {
            "title": "애니메이션 성지순례 가이드 - 실제 애니 배경지 방문",
            "category": "문화",
            "city": "일본 각지",
            "description": "『너의 이름은』의 스가신사부터 『센과 치히로의 행방불명』의 모델지까지. 애니 성지순례 가이드.",
        },
        "es": {
            "title": "Guía de Peregrinación Anime - Visita Lugares Reales del Anime",
            "category": "Cultura",
            "city": "Varios",
            "description": "Visita los lugares reales que inspiraron tu anime favorito, desde el Santuario Suga de Your Name hasta la casa de baños de El Viaje de Chihiro.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Akihabara_2012.jpg/1280px-Akihabara_2012.jpg",
        "tags_en": ["anime", "pilgrimage", "otaku", "culture"],
        "tags_ja": ["アニメ", "聖地巡礼", "オタク", "文化"],
        "tags_zh": ["动漫", "圣地巡礼", "宅文化", "文化"],
        "tags_ko": ["애니메이션", "성지순례", "오타쿠", "문화"],
        "tags_es": ["anime", "peregrinación", "otaku", "cultura"],
    },
    {
        "slug": "japan-manners",
        "en": {
            "title": "Japanese Manners Guide - Do's and Don'ts for Visitors",
            "category": "Culture",
            "city": "Various",
            "description": "Essential etiquette tips for visiting Japan: bowing, chopstick rules, shoe etiquette, and common cultural faux pas to avoid.",
        },
        "ja": {
            "title": "日本のマナーガイド - 訪日観光客の心得",
            "category": "文化",
            "city": "全国",
            "description": "お辞儀、箸のマナー、靴の脱ぎ方。外国人旅行者が知っておくべき日本のマナーを解説。",
        },
        "zh": {
            "title": "日本礼仪指南 - 游客须知",
            "category": "文化",
            "city": "日本各地",
            "description": "访问日本的必备礼仪提示：鞠躬、筷子规则、脱鞋礼仪和常见文化禁忌。",
        },
        "ko": {
            "title": "일본 매너 가이드 - 방문자를 위한 에티켓",
            "category": "문화",
            "city": "일본 각지",
            "description": "인사, 젓가락 매너, 신발 벗기. 외국인 여행자가 알아야 할 일본 매너를 해설합니다.",
        },
        "es": {
            "title": "Guía de Modales Japoneses - Lo Que Hacer y No Hacer",
            "category": "Cultura",
            "city": "Varios",
            "description": "Consejos esenciales de etiqueta para visitar Japón: reverencias, reglas de palillos, etiqueta del calzado y errores culturales comunes.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Tokyostation.jpg/1280px-Tokyostation.jpg",
        "tags_en": ["manners", "etiquette", "tips", "culture"],
        "tags_ja": ["マナー", "エチケット", "ヒント", "文化"],
        "tags_zh": ["礼仪", "礼节", "提示", "文化"],
        "tags_ko": ["매너", "에티켓", "팁", "문화"],
        "tags_es": ["modales", "etiqueta", "consejos", "cultura"],
    },
    {
        "slug": "shinkansen-guide",
        "en": {
            "title": "Shinkansen Guide - Riding Japan's Bullet Train",
            "category": "Culture",
            "city": "Various",
            "description": "Master the Shinkansen: how to book tickets, which seat to choose for the best views, and tips for a smooth journey.",
        },
        "ja": {
            "title": "新幹線の乗り方ガイド - 快適な旅のコツ",
            "category": "文化",
            "city": "全国",
            "description": "チケットの予約方法、富士山が見える座席、車内の過ごし方。新幹線を快適に楽しむコツを紹介。",
        },
        "zh": {
            "title": "新干线指南 - 乘坐日本子弹头列车",
            "category": "文化",
            "city": "日本各地",
            "description": "掌握新干线：如何预订车票、选择最佳景观座位，以及顺畅旅途的提示。",
        },
        "ko": {
            "title": "신칸센 가이드 - 일본 고속열차 타기",
            "category": "문화",
            "city": "일본 각지",
            "description": "티켓 예약, 후지산이 보이는 좌석, 차내 즐기기. 신칸센을 편안하게 즐기는 법을 소개합니다.",
        },
        "es": {
            "title": "Guía del Shinkansen - Montando el Tren Bala de Japón",
            "category": "Cultura",
            "city": "Varios",
            "description": "Domina el Shinkansen: cómo reservar billetes, qué asiento elegir para las mejores vistas y consejos para un viaje fluido.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Shinkansen_N700_with_arrow.jpg/1280px-Shinkansen_N700_with_arrow.jpg",
        "tags_en": ["shinkansen", "bullet-train", "transport", "travel-tips"],
        "tags_ja": ["新幹線", "弾丸列車", "交通", "旅行のコツ"],
        "tags_zh": ["新干线", "子弹头列车", "交通", "旅行提示"],
        "tags_ko": ["신칸센", "고속열차", "교통", "여행팁"],
        "tags_es": ["shinkansen", "tren-bala", "transporte", "consejos-de-viaje"],
    },
    {
        "slug": "jr-pass-guide",
        "en": {
            "title": "JR Pass Complete Guide - Is It Worth It?",
            "category": "Culture",
            "city": "Various",
            "description": "Everything about the Japan Rail Pass: pricing, how to use it, which routes it covers, and whether it's worth buying.",
        },
        "ja": {
            "title": "JRパス完全ガイド - お得な使い方",
            "category": "文化",
            "city": "全国",
            "description": "ジャパンレールパスの料金、使い方、対象路線、そしてお得に使うコツを完全解説。",
        },
        "zh": {
            "title": "JR通票完全指南 - 值得买吗？",
            "category": "文化",
            "city": "日本各地",
            "description": "关于日本铁路通票的一切：定价、使用方法、覆盖路线以及是否值得购买。",
        },
        "ko": {
            "title": "JR패스 완전 가이드 - 살 가치가 있을까?",
            "category": "문화",
            "city": "일본 각지",
            "description": "재팬 레일 패스의 가격, 사용법, 대상 노선, 그리고 알뜰하게 사용하는 팁을 완전 해설.",
        },
        "es": {
            "title": "Guía Completa del JR Pass - ¿Vale la Pena?",
            "category": "Cultura",
            "city": "Varios",
            "description": "Todo sobre el Japan Rail Pass: precios, cómo usarlo, qué rutas cubre y si vale la pena comprarlo.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/JR_East_Shinkansen_lineup_at_Niigata_Depot_200910.jpg/1280px-JR_East_Shinkansen_lineup_at_Niigata_Depot_200910.jpg",
        "tags_en": ["jr-pass", "rail-pass", "transport", "budget"],
        "tags_ja": ["JRパス", "レールパス", "交通", "節約"],
        "tags_zh": ["JR通票", "铁路通票", "交通", "省钱"],
        "tags_ko": ["JR패스", "레일패스", "교통", "절약"],
        "tags_es": ["jr-pass", "pase-de-tren", "transporte", "presupuesto"],
    },
    {
        "slug": "konbini-guide",
        "en": {
            "title": "Japanese Convenience Store Guide - Konbini Magic",
            "category": "Culture",
            "city": "Various",
            "description": "Discover why Japanese convenience stores are a tourist attraction in themselves: amazing food, services, and hidden gems at every konbini.",
        },
        "ja": {
            "title": "コンビニ活用術 - 旅行者のための完全ガイド",
            "category": "文化",
            "city": "全国",
            "description": "おにぎり、スイーツ、ATM、Wi-Fi。日本のコンビニを120%活用する方法を旅行者目線で紹介。",
        },
        "zh": {
            "title": "日本便利店指南 - 便利店的魔力",
            "category": "文化",
            "city": "日本各地",
            "description": "发现为什么日本便利店本身就是一个旅游景点：每家便利店都有令人惊叹的美食、服务和隐藏宝藏。",
        },
        "ko": {
            "title": "일본 편의점 가이드 - 콘비니의 마법",
            "category": "문화",
            "city": "일본 각지",
            "description": "오니기리, 스위츠, ATM, Wi-Fi. 일본 편의점을 120% 활용하는 법을 여행자 시점으로 소개합니다.",
        },
        "es": {
            "title": "Guía de Tiendas de Conveniencia Japonesas - La Magia del Konbini",
            "category": "Cultura",
            "city": "Varios",
            "description": "Descubre por qué las tiendas de conveniencia japonesas son una atracción turística en sí mismas: comida increíble, servicios y joyas ocultas.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/FamilyMart_Higashiginza-Showa-dori_store.jpg/1280px-FamilyMart_Higashiginza-Showa-dori_store.jpg",
        "tags_en": ["konbini", "convenience-store", "tips", "food"],
        "tags_ja": ["コンビニ", "便利", "ヒント", "グルメ"],
        "tags_zh": ["便利店", "方便", "提示", "美食"],
        "tags_ko": ["편의점", "편리", "팁", "음식"],
        "tags_es": ["konbini", "tienda-de-conveniencia", "consejos", "comida"],
    },
    # ==================== NATURE (41-50) ====================
    {
        "slug": "mount-fuji",
        "en": {
            "title": "Mount Fuji Climbing Guide - Conquering Japan's Highest Peak",
            "category": "Nature",
            "city": "Shizuoka/Yamanashi",
            "description": "Everything you need to climb Mount Fuji: trail options, best season, what to pack, and tips for reaching the summit.",
        },
        "ja": {
            "title": "富士山登山ガイド - 日本最高峰を制覇",
            "category": "自然",
            "city": "静岡/山梨",
            "description": "登山ルート、ベストシーズン、装備リスト、ご来光のコツ。富士山登頂を完全サポートするガイド。",
        },
        "zh": {
            "title": "富士山攀登指南 - 征服日本最高峰",
            "category": "自然",
            "city": "静冈/山梨",
            "description": "攀登富士山所需的一切：路线选择、最佳季节、装备清单和登顶技巧。",
        },
        "ko": {
            "title": "후지산 등산 가이드 - 일본 최고봉 정복",
            "category": "자연",
            "city": "시즈오카/야마나시",
            "description": "등산 루트, 베스트 시즌, 장비 리스트, 일출 팁. 후지산 등정을 완전 서포트하는 가이드.",
        },
        "es": {
            "title": "Guía para Escalar el Monte Fuji - Conquistando el Pico Más Alto de Japón",
            "category": "Naturaleza",
            "city": "Shizuoka/Yamanashi",
            "description": "Todo lo que necesitas para escalar el Monte Fuji: opciones de senderos, mejor temporada, qué empacar y consejos para llegar a la cima.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Mount_Fuji_from_Hotel_Mt_Fuji_1995-2-7.jpg/1280px-Mount_Fuji_from_Hotel_Mt_Fuji_1995-2-7.jpg",
        "tags_en": ["mount-fuji", "hiking", "climbing", "nature"],
        "tags_ja": ["富士山", "登山", "ハイキング", "自然"],
        "tags_zh": ["富士山", "登山", "徒步", "自然"],
        "tags_ko": ["후지산", "등산", "하이킹", "자연"],
        "tags_es": ["monte-fuji", "senderismo", "escalada", "naturaleza"],
    },
    {
        "slug": "cherry-blossom-spots",
        "en": {
            "title": "Top 10 Cherry Blossom Spots in Japan",
            "category": "Nature",
            "city": "Various",
            "description": "The ultimate guide to Japan's best cherry blossom viewing spots, with bloom forecasts and photography tips.",
        },
        "ja": {
            "title": "桜の名所TOP10 - お花見スポット厳選ガイド",
            "category": "自然",
            "city": "全国",
            "description": "開花予想、撮影のコツ付き。日本全国から厳選した桜の名所トップ10を紹介。",
        },
        "zh": {
            "title": "日本十大赏樱胜地",
            "category": "自然",
            "city": "日本各地",
            "description": "日本最佳赏樱地点终极指南，附花期预测和摄影技巧。",
        },
        "ko": {
            "title": "일본 벚꽃 명소 TOP 10",
            "category": "자연",
            "city": "일본 각지",
            "description": "개화 예상, 촬영 팁 포함. 일본 전국에서 엄선한 벚꽃 명소 톱 10을 소개합니다.",
        },
        "es": {
            "title": "Los 10 Mejores Lugares para Ver Cerezos en Flor en Japón",
            "category": "Naturaleza",
            "city": "Varios",
            "description": "La guía definitiva de los mejores lugares para ver cerezos en flor en Japón, con pronósticos de floración y consejos de fotografía.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Chidorigafuchi_2009.jpg/1280px-Chidorigafuchi_2009.jpg",
        "tags_en": ["cherry-blossom", "sakura", "spring", "nature"],
        "tags_ja": ["桜", "さくら", "春", "自然"],
        "tags_zh": ["樱花", "樱", "春天", "自然"],
        "tags_ko": ["벚꽃", "사쿠라", "봄", "자연"],
        "tags_es": ["cerezos-en-flor", "sakura", "primavera", "naturaleza"],
    },
    {
        "slug": "autumn-leaves-spots",
        "en": {
            "title": "Top 10 Autumn Leaves Spots in Japan",
            "category": "Nature",
            "city": "Various",
            "description": "Japan's most stunning autumn foliage locations, with the best times to visit and tips for capturing the perfect photo.",
        },
        "ja": {
            "title": "紅葉の名所TOP10 - 秋の絶景スポット",
            "category": "自然",
            "city": "全国",
            "description": "見頃時期、撮影のコツ付き。日本全国から厳選した紅葉の名所トップ10を紹介。",
        },
        "zh": {
            "title": "日本十大赏红叶胜地",
            "category": "自然",
            "city": "日本各地",
            "description": "日本最壮观的红叶景点，附最佳访问时间和完美拍照技巧。",
        },
        "ko": {
            "title": "일본 단풍 명소 TOP 10",
            "category": "자연",
            "city": "일본 각지",
            "description": "절정 시기, 촬영 팁 포함. 일본 전국에서 엄선한 단풍 명소 톱 10을 소개합니다.",
        },
        "es": {
            "title": "Los 10 Mejores Lugares para Ver Hojas de Otoño en Japón",
            "category": "Naturaleza",
            "city": "Varios",
            "description": "Los lugares más impresionantes de follaje otoñal en Japón, con los mejores momentos para visitar y consejos para la foto perfecta.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Kiyomizu-dera_in_Kyoto-r.jpg/1280px-Kiyomizu-dera_in_Kyoto-r.jpg",
        "tags_en": ["autumn-leaves", "koyo", "fall", "nature"],
        "tags_ja": ["紅葉", "もみじ", "秋", "自然"],
        "tags_zh": ["红叶", "枫叶", "秋天", "自然"],
        "tags_ko": ["단풍", "모미지", "가을", "자연"],
        "tags_es": ["hojas-de-otoño", "koyo", "otoño", "naturaleza"],
    },
    {
        "slug": "yakushima",
        "en": {
            "title": "Yakushima - Ancient Forest Island of the Gods",
            "category": "Nature",
            "city": "Kagoshima",
            "description": "Trek through Yakushima's ancient cedar forests, the inspiration for Princess Mononoke, and home to trees over 7,000 years old.",
        },
        "ja": {
            "title": "屋久島 - もののけ姫の森を歩く",
            "category": "自然",
            "city": "鹿児島",
            "description": "樹齢7000年超の縄文杉、もののけ姫の舞台。太古の森が広がる世界遺産・屋久島を紹介。",
        },
        "zh": {
            "title": "屋久岛 - 众神的古老森林之岛",
            "category": "自然",
            "city": "�的儿岛",
            "description": "穿越屋久岛古老的杉树林，《幽灵公主》的灵感来源，拥有超过7000年历史的古树。",
        },
        "ko": {
            "title": "야쿠시마 - 신들의 고대 숲 섬",
            "category": "자연",
            "city": "가고시마",
            "description": "수령 7000년의 조몬삼나무, 모노노케히메의 무대. 태고의 숲이 펼쳐진 세계유산 야쿠시마를 소개.",
        },
        "es": {
            "title": "Yakushima - Isla del Bosque Antiguo de los Dioses",
            "category": "Naturaleza",
            "city": "Kagoshima",
            "description": "Camina por los antiguos bosques de cedros de Yakushima, inspiración de La Princesa Mononoke, hogar de árboles de más de 7,000 años.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Yakushima_Jomon_Sugi_01.jpg/800px-Yakushima_Jomon_Sugi_01.jpg",
        "tags_en": ["yakushima", "forest", "hiking", "world-heritage"],
        "tags_ja": ["屋久島", "森", "トレッキング", "世界遺産"],
        "tags_zh": ["屋久岛", "森林", "徒步", "世界遗产"],
        "tags_ko": ["야쿠시마", "숲", "트레킹", "세계유산"],
        "tags_es": ["yakushima", "bosque", "senderismo", "patrimonio-mundial"],
    },
    {
        "slug": "shirakawago",
        "en": {
            "title": "Shirakawa-go - Traditional Thatched-Roof Village",
            "category": "Nature",
            "city": "Gifu",
            "description": "Visit the UNESCO World Heritage village of Shirakawa-go, famous for its traditional gassho-zukuri farmhouses.",
        },
        "ja": {
            "title": "白川郷 - 合掌造りの里",
            "category": "自然",
            "city": "岐阜",
            "description": "世界遺産・白川郷の合掌造り集落。冬のライトアップは幻想的な美しさ。四季の魅力を紹介。",
        },
        "zh": {
            "title": "白川乡 - 传统茅草屋顶村庄",
            "category": "自然",
            "city": "岐阜",
            "description": "参观联合国教科文组织世界遗产白川乡，以传统合掌造农舍闻名。",
        },
        "ko": {
            "title": "시라카와고 - 전통 갓쇼즈쿠리 마을",
            "category": "자연",
            "city": "기후",
            "description": "세계유산 시라카와고의 갓쇼즈쿠리 마을. 겨울 라이트업의 환상적인 아름다움을 소개합니다.",
        },
        "es": {
            "title": "Shirakawa-go - Aldea Tradicional de Techos de Paja",
            "category": "Naturaleza",
            "city": "Gifu",
            "description": "Visita la aldea Patrimonio de la Humanidad de Shirakawa-go, famosa por sus tradicionales casas gassho-zukuri.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Shirakawa-go%2C_Gifu%2C_Japan.jpg/1280px-Shirakawa-go%2C_Gifu%2C_Japan.jpg",
        "tags_en": ["shirakawa-go", "village", "world-heritage", "winter"],
        "tags_ja": ["白川郷", "集落", "世界遺産", "冬"],
        "tags_zh": ["白川乡", "村庄", "世界遗产", "冬天"],
        "tags_ko": ["시라카와고", "마을", "세계유산", "겨울"],
        "tags_es": ["shirakawa-go", "aldea", "patrimonio-mundial", "invierno"],
    },
    {
        "slug": "tateyama-kurobe",
        "en": {
            "title": "Tateyama Kurobe Alpine Route - Snow Walls and Mountain Scenery",
            "category": "Nature",
            "city": "Toyama/Nagano",
            "description": "Travel the spectacular Tateyama Kurobe Alpine Route with its famous 20-meter snow walls and breathtaking mountain views.",
        },
        "ja": {
            "title": "立山黒部アルペンルート - 雪の大谷と絶景",
            "category": "自然",
            "city": "富山/長野",
            "description": "高さ20mの雪の大谷、黒部ダム、室堂の絶景。立山黒部アルペンルートの見どころを完全ガイド。",
        },
        "zh": {
            "title": "立山黑部阿尔卑斯路线 - 雪壁与山景",
            "category": "自然",
            "city": "富山/长野",
            "description": "游览壮观的立山黑部阿尔卑斯路线，拥有著名的20米雪壁和令人叹为观止的山景。",
        },
        "ko": {
            "title": "다테야마 쿠로베 알펜루트 - 눈의 대계곡과 산 풍경",
            "category": "자연",
            "city": "도야마/나가노",
            "description": "높이 20m의 눈의 대계곡, 쿠로베 댐, 무로도의 절경. 다테야마 쿠로베 알펜루트를 완전 가이드.",
        },
        "es": {
            "title": "Ruta Alpina Tateyama Kurobe - Muros de Nieve y Paisajes de Montaña",
            "category": "Naturaleza",
            "city": "Toyama/Nagano",
            "description": "Recorre la espectacular Ruta Alpina Tateyama Kurobe con sus famosos muros de nieve de 20 metros y vistas montañosas impresionantes.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Tateyama_Kurobe_Alpine_Route_01.jpg/1280px-Tateyama_Kurobe_Alpine_Route_01.jpg",
        "tags_en": ["tateyama", "alpine", "snow-wall", "mountains"],
        "tags_ja": ["立山", "アルペン", "雪の大谷", "山"],
        "tags_zh": ["立山", "阿尔卑斯", "雪壁", "山"],
        "tags_ko": ["다테야마", "알펜", "눈의대계곡", "산"],
        "tags_es": ["tateyama", "alpino", "muro-de-nieve", "montañas"],
    },
    {
        "slug": "takeda-castle",
        "en": {
            "title": "Takeda Castle Ruins - The Castle in the Sky",
            "category": "Nature",
            "city": "Hyogo",
            "description": "Witness the magical Takeda Castle ruins floating above the clouds, often called Japan's Machu Picchu.",
        },
        "ja": {
            "title": "竹田城跡 - 天空の城",
            "category": "自然",
            "city": "兵庫",
            "description": "雲海に浮かぶ「天空の城」。日本のマチュピチュとも呼ばれる竹田城跡の幻想的な絶景を紹介。",
        },
        "zh": {
            "title": "竹田城迹 - 天空之城",
            "category": "自然",
            "city": "�的库",
            "description": "见证漂浮在云海之上的竹田城遗迹，常被称为日本的马丘比丘。",
        },
        "ko": {
            "title": "다케다 성터 - 하늘의 성",
            "category": "자연",
            "city": "효고",
            "description": "운해에 떠있는 '하늘의 성'. 일본의 마추픽추라 불리는 다케다 성터의 환상적 절경을 소개합니다.",
        },
        "es": {
            "title": "Ruinas del Castillo Takeda - El Castillo en el Cielo",
            "category": "Naturaleza",
            "city": "Hyogo",
            "description": "Contempla las mágicas ruinas del Castillo Takeda flotando sobre las nubes, a menudo llamado el Machu Picchu de Japón.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Takeda_castle_09.jpg/1280px-Takeda_castle_09.jpg",
        "tags_en": ["castle", "cloud-sea", "hyogo", "ruins"],
        "tags_ja": ["城", "雲海", "兵庫", "城跡"],
        "tags_zh": ["城堡", "云海", "兵库", "遗迹"],
        "tags_ko": ["성", "운해", "효고", "성터"],
        "tags_es": ["castillo", "mar-de-nubes", "hyogo", "ruinas"],
    },
    {
        "slug": "biei-blue-pond",
        "en": {
            "title": "Blue Pond of Biei - Hokkaido's Mystical Lake",
            "category": "Nature",
            "city": "Hokkaido",
            "description": "Visit the stunning Blue Pond in Biei, Hokkaido, famous for its otherworldly cobalt blue water and ghostly birch trees.",
        },
        "ja": {
            "title": "美瑛・青い池 - 北海道の神秘の湖",
            "category": "自然",
            "city": "北海道",
            "description": "Apple社の壁紙にも採用された神秘的なコバルトブルーの青い池。美瑛の絶景スポットを紹介。",
        },
        "zh": {
            "title": "美瑛青池 - 北海道的神秘湖泊",
            "category": "自然",
            "city": "北海道",
            "description": "参观美瑛令人惊叹的青池，以其超凡脱俗的钴蓝色湖水和幽灵般的白桦树闻名。",
        },
        "ko": {
            "title": "비에이 청의 연못 - 홋카이도의 신비로운 호수",
            "category": "자연",
            "city": "홋카이도",
            "description": "Apple 배경화면에도 채택된 신비로운 코발트 블루의 청의 연못. 비에이의 절경 스팟을 소개합니다.",
        },
        "es": {
            "title": "Estanque Azul de Biei - El Lago Místico de Hokkaido",
            "category": "Naturaleza",
            "city": "Hokkaido",
            "description": "Visita el impresionante Estanque Azul de Biei, famoso por su agua azul cobalto sobrenatural y sus fantasmales abedules.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Blue_Pond_Hokkaido.jpg/1280px-Blue_Pond_Hokkaido.jpg",
        "tags_en": ["blue-pond", "biei", "hokkaido", "mystical"],
        "tags_ja": ["青い池", "美瑛", "北海道", "神秘"],
        "tags_zh": ["青池", "美瑛", "北海道", "神秘"],
        "tags_ko": ["청의연못", "비에이", "홋카이도", "신비"],
        "tags_es": ["estanque-azul", "biei", "hokkaido", "místico"],
    },
    {
        "slug": "arashiyama-bamboo",
        "en": {
            "title": "Arashiyama Bamboo Grove - Kyoto's Enchanted Forest",
            "category": "Nature",
            "city": "Kyoto",
            "description": "Walk through the towering bamboo stalks of Arashiyama, one of Kyoto's most magical and photographed natural wonders.",
        },
        "ja": {
            "title": "嵐山竹林 - 京都の幻想の森",
            "category": "自然",
            "city": "京都",
            "description": "天に向かってそびえる竹の回廊。京都・嵐山の竹林の小径は、幻想的な美しさに満ちている。",
        },
        "zh": {
            "title": "岚山竹林 - 京都的魔法森林",
            "category": "自然",
            "city": "京都",
            "description": "漫步于岚山高耸的竹林中，这是京都最神奇且最常被拍摄的自然奇观之一。",
        },
        "ko": {
            "title": "아라시야마 대나무숲 - 교토의 마법의 숲",
            "category": "자연",
            "city": "교토",
            "description": "하늘을 향해 솟은 대나무 회랑. 교토 아라시야마의 대나무숲은 환상적인 아름다움으로 가득합니다.",
        },
        "es": {
            "title": "Bosque de Bambú de Arashiyama - El Bosque Encantado de Kioto",
            "category": "Naturaleza",
            "city": "Kioto",
            "description": "Camina entre los imponentes tallos de bambú de Arashiyama, una de las maravillas naturales más mágicas y fotografiadas de Kioto.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Bamboo_forest%2C_Arashiyama%2C_Kyoto%2C_Japan.jpg/800px-Bamboo_forest%2C_Arashiyama%2C_Kyoto%2C_Japan.jpg",
        "tags_en": ["bamboo", "arashiyama", "kyoto", "forest"],
        "tags_ja": ["竹林", "嵐山", "京都", "森"],
        "tags_zh": ["竹林", "岚山", "京都", "森林"],
        "tags_ko": ["대나무숲", "아라시야마", "교토", "숲"],
        "tags_es": ["bambú", "arashiyama", "kioto", "bosque"],
    },
    {
        "slug": "setouchi-art-islands",
        "en": {
            "title": "Setouchi Art Islands - Where Art Meets the Sea",
            "category": "Nature",
            "city": "Kagawa/Okayama",
            "description": "Explore the art islands of the Seto Inland Sea: Naoshima, Teshima, and Inujima, where contemporary art blends with island life.",
        },
        "ja": {
            "title": "瀬戸内海アート島巡り - アートと海が出会う場所",
            "category": "自然",
            "city": "香川/岡山",
            "description": "直島、豊島、犬島。瀬戸内海に浮かぶアートの島々で、現代アートと島の暮らしの融合を体験。",
        },
        "zh": {
            "title": "濑户内艺术岛 - 艺术与海的相遇",
            "category": "自然",
            "city": "香川/冈山",
            "description": "探索濑户内海的艺术岛屿：直岛、�的岛和犬岛，现代艺术与岛屿生活的融合。",
        },
        "ko": {
            "title": "세토우치 아트 섬 투어 - 예술과 바다가 만나는 곳",
            "category": "자연",
            "city": "가가와/오카야마",
            "description": "나오시마, 데시마, 이누지마. 세토내해에 떠있는 아트 섬에서 현대미술과 섬 생활의 융합을 체험.",
        },
        "es": {
            "title": "Islas de Arte del Setouchi - Donde el Arte se Encuentra con el Mar",
            "category": "Naturaleza",
            "city": "Kagawa/Okayama",
            "description": "Explora las islas de arte del Mar Interior de Seto: Naoshima, Teshima e Inujima, donde el arte contemporáneo se funde con la vida isleña.",
        },
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Naoshima_-_panoramio.jpg/1280px-Naoshima_-_panoramio.jpg",
        "tags_en": ["art", "islands", "naoshima", "setouchi"],
        "tags_ja": ["アート", "島", "直島", "瀬戸内"],
        "tags_zh": ["艺术", "岛屿", "直岛", "濑户内"],
        "tags_ko": ["아트", "섬", "나오시마", "세토우치"],
        "tags_es": ["arte", "islas", "naoshima", "setouchi"],
    },
]

LANGUAGES = ["en", "ja", "zh", "ko", "es"]
